language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t karlfock/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karlfock/react-test npm test

after_success:
  - docker build -t karlfock/multi-client ./client
  - docker build -t karlfock/multi-nginx ./nginx
  - docker build -t karlfock/multi-server ./server
  - docker build -t karlfock/multi-worker ./worker
  # Log in to the docke CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push karlfock/multi-client
  - docker push karlfock/multi-nginx
  - docker push karlfock/multi-server
  - docker push karlfock/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-903342119671
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
